{{- range $secret := .Values.secrets }}
{{- if $secret.create }}
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ regexReplaceAll "[.]" $secret.name "-" }}
data:
  {{ $secret.key | default $secret.name }}: |
{{ tpl $secret.data $ | indent 6 }}
---
{{- end }}
{{- end }}

{{- if .Values.vpn.enabled }}
{{- if .Values.vpn.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vpn.secretName }}
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
type: Opaque
data:
  wg0.conf: |
    {{ .Values.vpn.config | b64enc | quote }}
{{- end }}
{{- end }}